### ISSUE TITLE
Laravel 5.2 Support?

### ISSUE THREAD

**Issue by dongkaipo** [lucadegasperi/oauth2-server-laravel#636] opened 2016-01-04 03:21 UTC
```
 - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6].
    - Installation request for lucadegasperi/oauth2-server-laravel 5.0.* -> satisfiable by lucadegasperi/oauth2-server-laravel[5.0.0, 5.0.1, 5.0.2, 5.0.3].
```

Is it support 5.2 now?

**Comment by vinkla** [comment] 2016-01-04 19:00
Thanks for reporting. This is a duplicate of #634 and we can continue there.

**Closed by vinkla** 2016-01-04 19:00 UTC

**Comment by dongkaipo** [comment] 2016-01-05 02:23
Thanks :+1:  : )
