### ISSUE TITLE
Error Fetching Access Tokens

### ISSUE THREAD

**Issue by marktopper** [lucadegasperi/oauth2-server-laravel#602] opened 2015-11-18 13:01 UTC
Suddently I started to get this right out of nowhere.

```
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."
}
```

Sometimes it works, sometimes not...

I just created a token using the method with `grant_type = password`.
```
return \Response::json(\Authorizer::issueAccessToken());
```

My configurations are the following:
```
<?php
return [
    'database' => 'default',
    'grant_types' => [
	    'password' => [
	        'class' => League\OAuth2\Server\Grant\PasswordGrant::class,
	        'callback' => '\Puzzible\OAuth2\Verifier@verify',
	        'access_token_ttl' => 3600
	    ],
	    'facebook' => [
	        'class' => Puzzible\OAuth2\Grants\FacebookTokenGrant::class,
	        'callback' => '\Puzzible\OAuth2\Verifier@verifyFacebook',
	        'access_token_ttl' => 3600
	    ],
	    'twitter' => [
	        'class' => Puzzible\OAuth2\Grants\TwitterTokenGrant::class,
	        'callback' => '\Puzzible\OAuth2\Verifier@verifyTwitter',
	        'access_token_ttl' => 3600
	    ],
    ],
    'token_type' => League\OAuth2\Server\TokenType\Bearer::class,
    'state_param' => false,
    'scope_param' => false,
    'scope_delimiter' => ',',
    'default_scope' => null,
    'access_token_ttl' => 3600,
    'limit_clients_to_grants' => false,
    'limit_clients_to_scopes' => false,
    'limit_scopes_to_grants' => false,
    'http_headers_only' => false,
];
```

Any ideas how to fix this issue?

**Comment by marktopper** [comment] 2015-11-18 13:15
I tried to change composer.json to use the following package versions:
```
league/oauth2-server (4.1.3) instead of league/oauth2-server (4.1.4)
lucadegasperi/oauth2-server-laravel (5.0.2) instead of lucadegasperi/oauth2-server-laravel (5.0.3)
```

Now it works on one of my two web servers, any ideas why this can be?
They have the exact same code deployed...

**Comment by tuupke** [comment] 2015-11-25 12:08
I had this exact issue, it is in the league package, the authorization header gets completely converted to lowercase while the token verifier looks for "Authorization" which it cannot find for obvious reasons.

This was not yet the case in the old version (4.1.3) so requiring that version in your composer.json should solve the issue for now.

**Comment by vinkla** [comment] 2015-12-02 07:45
This only happened with the latest version?

**Comment by marktopper** [comment] 2015-12-02 08:05
From what I know, yes @vinkla.

**Comment by vinkla** [comment] 2015-12-02 08:07
I'm using the latest version of this package with the latest version of Laravel without any problems.

**Comment by vinkla** [comment] 2015-12-02 08:13
Lets close this for now and if anyone else have this problem we will take it from there. Thanks for reporting!

**Comment by vinkla** [comment] 2015-12-02 10:24
Now this is also reported in #612. @alexbilbie do you know why this could happened?

**Comment by PrashanthRaghu** [comment] 2015-12-02 10:26
I am also getting the same issue.

**Comment by guilhermesoratto** [comment] 2015-12-07 19:11
I am having the same problem, I can solve it temporarily?

**Comment by vinkla** [comment] 2015-12-07 21:48
Now this is also reported in #612. @alexbilbie @lucadegasperi do you guys know why this could happened?

**Comment by guilhermesoratto** [comment] 2015-12-07 22:25
@marktopper @vinkla @lucadegasperi I found this same problem and the solution to this issue I added the following line in the .htaccess file, I think that is an Apache problem.


RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization},last]

**Comment by vinkla** [comment] 2015-12-12 23:13
@marktopper @tuupke does the comment by @guilhermesoratto above solve your issue?

**Comment by tuupke** [comment] 2015-12-13 11:05
@vinkla Well, I'm running nginx, but even with its version of that command, it will not be fixed; Somewhere the headers were converted to lowercase while it checked for the "Authorization" header which it could not find since the capitol A got converted to lowercase. But as I said, the problem was not caused by this package, but by the league's package. So reverting that back to 4.1.3 was the easiest fix.

**Comment by marktopper** [comment] 2015-12-14 12:04
@vinkla, I am running nginx as well. So can't help with checking that.

**Comment by vinkla** [comment] 2015-12-18 12:11
I'm also running NGINX without any issues at all. Closing this for now.

**Closed by vinkla** 2015-12-18 12:11 UTC
Labels: bug

**Comment by rizkytahara** [comment] 2015-12-26 16:36
@tuupke Thank's.. it works after downgrading the league's package to 4.1.3

**Comment by oflannabhra** [comment] 2016-02-02 20:09
I'm using nginx 1.8 and am having the same issue with the Authorization Header getting stripped out of the request.
