### ISSUE TITLE
CORS header 

### ISSUE THREAD

**Issue by developernaren** [lucadegasperi/oauth2-server-laravel#466] opened 2015-07-17 11:45 UTC
I am trying to create an oauth resource server and I am using Lumen. The request come in from a different domain, So I should allow all the request to come in.
I have used a Middleware

    class CorsMiddleware {

    public function handle($request, \Closure $next) {
        $response = $next($request);

        $response->header('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE, OPTIONS');
        $response->header('Access-Control-Allow-Headers', $request->header('Access-Control-Request-Headers'));
        $response->header('Access-Control-Allow-Origin', '*');

        return $response;
    }

    }
which attached headers to all the response. This is working fine except for when the username/ password is invalid. Lumen does not hit the this method, instead I see that it throws an exception. I tried to catch it with this

    $app->error(function(League\OAuth2\Server\Exception\OAuthException $exception)
     {
    $response = Response::make([
        'error'   => $exception->errorType,
        'message' => $exception->getMessage()
    ], 401);

        $response->header('Access-Control-Allow-Origin' , '*');
    $response->header('Access-Control-Allow-Methods', 'GET, POST, PUT, OPTIONS');
    $response->header('Access-Control-Allow-Headers', 'Origin, Content-Type, Accept, Authorization');

    return $response;
    });

a solution suggested by [@JoeyHoutenbos](https://github.com/JoeyHoutenbos)

But none of these seem to work and this method seems to override all this and the header is sent empty because of this method 

     public function getHttpHeaders()
        {

        $headers = [];        
        switch ($this->httpStatusCode) {
            case 401:
                $headers[] = 'HTTP/1.1 401 Unauthorized';
                break;
            case 500:
                $headers[] = 'HTTP/1.1 500 Internal Server Error';
                break;
            case 501:
                $headers[] = 'HTTP/1.1 501 Not Implemented';
                break;
            case 400:
            default:
                $headers[] = 'HTTP/1.1 400 Bad Request';
                break;
            }

`League\OAuth2\Server\Exception\OAuthException;`

I literally get the status code in my `headers 0 index` in my angular app

to fix this I changed the code to 

    $headers = [];        
            $headers ['Access-Control-Allow-Methods'] = 'HEAD, GET, POST, PUT, PATCH, DELETE,        OPTIONS';
                $headers ['Access-Control-Allow-Origin'] = '*';

and it is working like a charm.

Is there a way that this can be fixed without messing with the vendor file?

**Comment by lucadegasperi** [comment] 2015-07-18 09:01
Ask Alex, the maintainer of league/oauth2-server guess the problem is there.

**Comment by developernaren** [comment] 2015-07-20 06:18
I have posted an [issue](https://github.com/thephpleague/oauth2-server/issues/359) for this in [oauth2-server](https://github.com/thephpleague/oauth2-server) . If you can suggest or help please do or else you can close out this issue.
Thanks.

**Comment by vinkla** [comment] 2015-07-21 20:41
Since the question issue has been moved to league/oauth2-server I'll close this.

**Closed by vinkla** 2015-07-21 20:41 UTC
Labels: question

**Comment by developernaren** [comment] 2015-08-02 06:01
I have not gotten any reply to this over at the (alex's repo)[https://github.com/thephpleague/oauth2-server/issues/359] but I think I found the simplest solution to this and because I will use this in laravel only. I need your help.

So the way this can be solved is

adding a always present header of some other key in the `config file`.
    
        'additional_headers' => [

            'Access-Control-Allow-Methods' => 'HEAD, GET, POST, PUT, PATCH, DELETE, OPTIONS',
            'Access-Control-Allow-Origin' => '*'
        ]

and making the change to catch part to look like this

    $exceptionHeader = $e->getHttpHeaders();
            $headers = Config::get('oauth2.additional_headers');
            $headers[] = $exceptionHeader;

            return new JsonResponse([
                    'error'             => $e->errorType,
                    'error_description' => $e->getMessage()
                ],
                $e->httpStatusCode,
                $headers
                );

This will make it work for me, I tried and tested and this worked, and I can add additional headers that I would want to be present in the response in the config file. This can also be implemented in the in the try part for the CORS header support. I had to use a different `middleware` just for this. Please consider adding this into the package.

**Comment by vinkla** [comment] 2015-08-03 06:12
@developernaren Have you looked at [Laravel Cors](https://github.com/barryvdh/laravel-cors)? That package might help you.

**Comment by developernaren** [comment] 2015-08-03 06:30
So the way the package works is it uses as a wrapper for oauth-server which I am using for lumen.
So in essence there are too many packages intermingling into this I would not want to add another package.

Oauth-server-lumen uses oauth-server-laravel use oauth-server, so issue like this are hard to track and there are too many layers of exception handling to go through to make sure everything works. This I found is the easiest solution to this. A lot of my solutions failed because there are too many try catches going all around the package.

**Comment by vinkla** [comment] 2015-08-03 06:38
Yes, we'll leave it at that for now. Thanks for sharing your solutions!
